### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by giou**
fix syntax? pre-releases not updating

### CODE REVIEW

**Comment by tropicoo** [comment]
I believe it works, also, I've updated notification task.

**Comment by giou** [comment]
> I believe it works, also, I've updated notification task.

Good, can you check if it updates to latest prereasease? 2024.5.29.232700.dev0 as of now. It did not update for me.

**Comment by tropicoo** [comment]
Which command do you run?

**Comment by giou** [comment]
> Which command do you run?

`docker compose build --no-cache worker`

Works with the new syntax

**Comment by tropicoo** [comment]
1. 'app_worker/requirements.txt`: `yt-dlp>=2024.5.23.232707.dev0`
2.  `docker compose build --no-cache worker && docker compose up -d -t 0 worker`
3.  `GET {{base_host}}/v1/yt-dlp/?release_channel=NIGHTLY`
```json
{
    "latest": {
        "version": "2024.05.30.232720",
        "retrieved_at": "2024-05-31T22:10:09"
    },
    "current": {
        "version": "2024.05.30.232720",
        "updated_at": "2024-05-31T22:10:05"
    },
    "need_upgrade": false
}
```

**Comment by giou** [comment]
Just tested it with the new update and it works. Thanks!

But I think it looks cleaner with yt-dlp>=dev0

**Pull request closed without merging**
